print("---------------------------------------------------------------------------------------")
print("--------------------------------------WELCOME------------------------------------------")
priceone = input("price of item1:")
pricetwo = input("price of item2:")
pricethree = input("price of item3:")
print("---------------------------------------------------------------------------------------\n")
print("---------------------------------------------------------------------------------------")
print("discount details")
discountone = input("provide discount(in percentage) for 1st saver combo:")
discounttwo = input("provide discount(in percentage) for 2nd saver combo:")
discountthree = input("provide discount(in percentage) for 3rd saver combo:")
print("----------------------------------------------------------------------------------------\n")
contactnumber = input("provide your 10 digit contact number:")
print("---------------------------------------------------------------------------------------")
print("\nThe resulting calatog is:")
print("---------------------------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------")
print("delhi days")
print("R-block, model town 1")
print("delhi: 110009")
print("---------------------------------------------------------------------------------------")
print("---------------------------------------------------------------------------------------")
print("Item          Price(per pack)")
print()
print("Item1         " , priceone)
print("Item2         " , pricetwo)
print("Item3         " , pricethree)
print("combopack1    " , (0.01 * (100 - int(discountone)) * (int(priceone) + int(pricetwo))))
print("combopack2    " , (0.01 * (100 - int(discounttwo)) * (int(priceone) + int(pricethree))))
print("combopack3    " , (0.01 * (100 - int(discountthree)) * (int(pricetwo) + int(pricethree))))
print("supersaver    " , (0.01 * (100 - 28) * (int(pricetwo) + int(pricethree) + int(priceone))))
print("---------------------------------------------------------------------------------------")
print("For home delivery call at:",contactnumber)
print("---------------------------------------------------------------------------------------")