def cubing(x):
  n = x*x*x
  return n

def testing():
  f = open("IOpair.txt", "r")
  N = int(f.read())
  f.close()
  count=0
  for i in range(N):
    # Reading input files generated by generateData()
    f = open("File"+str(i)+".txt", "r")
    data = int(f.read())
    cubing_result = cubing(data)
    f.close()
    # Matching it with output file generated by generateData()
    f1 = open("ResultFile"+str(i)+".txt", "r")
    previous_result = int(f1.read())
    f1.close()
    if previous_result == cubing_result:
      count+=1
  if count == N :
    print("SUCCESS")
  else:
    print("FAILED")

testing()